package com.nbradbury.tictactroll.ui

import androidx.annotation.DrawableRes
import androidx.compose.foundation.Canvas
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.clipPath
import androidx.compose.ui.graphics.drawscope.withTransform
import androidx.compose.ui.res.imageResource
import com.nbradbury.tictactroll.R
import com.nbradbury.tictactroll.game.Team
import kotlin.math.min

/**
 * One eye's movable iris, in troll-image pixels: the sprite, where it sits at rest, the eye opening it's clipped to,
 * and how far it can travel sideways and vertically. Generated by .context/eyes/make_eyes.py, which also cut the
 * irises out of the base images.
 */
private class EyeSprite(
    @DrawableRes val iris: Int,
    val left: Float,
    val top: Float,
    val socket: Rect,
    val roomX: Float,
    val roomY: Float,
)

private val GORP_EYES = listOf(
    EyeSprite(R.drawable.troll_blue_iris0, 198f, 128f, Rect(200.5f, 130.5f, 227.5f, 150.1f), 4.7f, 9.8f),
    EyeSprite(R.drawable.troll_blue_iris1, 255f, 128f, Rect(257.2f, 130.6f, 290.8f, 150.6f), 8.0f, 10.0f),
)
private val BRAMBLE_EYES = listOf(
    EyeSprite(R.drawable.troll_red_iris0, 246f, 176f, Rect(248.5f, 178.2f, 293.5f, 199.8f), 9.7f, 10.8f),
    EyeSprite(R.drawable.troll_red_iris1, 346f, 176f, Rect(348.2f, 178.0f, 389.8f, 200.0f), 8.0f, 11.0f),
)

private val Team.eyes: List<EyeSprite> get() = if (this == Team.A) GORP_EYES else BRAMBLE_EYES

/** Eyelid skin, from each troll's cheeks, darkened toward the painted rim around the eyes. */
private val Team.lid: Color get() = if (this == Team.A) Color(0xFF6A8BAA) else Color(0xFF7A3428)

/** How much of an eye's room an iris uses at full gaze; less vertically, where the lids crowd it. */
private const val REACH_X = 0.75f
private const val REACH_Y = 0.25f

/**
 * A troll's picture whose irises look toward [lookX] and [lookY] (each -1 to 1, positive is right and down), with
 * eyelids closed by [blink] (0 open, 1 shut). Laid out like an Image with ContentScale.Fit and bottom-center alignment.
 */
@Composable
fun TrollArt(team: Team, modifier: Modifier = Modifier, lookX: Float = 0f, lookY: Float = 0f, blink: Float = 0f) {
    val base = ImageBitmap.imageResource(team.image)
    val eyes = team.eyes
    val irises = eyes.map { ImageBitmap.imageResource(it.iris) }
    val sockets = remember(team) { eyes.map { Path().apply { addOval(it.socket) } } }
    val lid = team.lid
    val lash = lid.copy(red = lid.red * 0.35f, green = lid.green * 0.35f, blue = lid.blue * 0.35f)
    Canvas(modifier) {
        val scale = min(size.width / base.width, size.height / base.height)
        val left = (size.width - base.width * scale) / 2
        val top = size.height - base.height * scale
        withTransform({
            translate(left, top)
            scale(scale, scale, pivot = Offset.Zero)
        }) {
            drawImage(base)
            eyes.forEachIndexed { i, eye ->
                clipPath(sockets[i]) {
                    val x = eye.left + lookX * eye.roomX * REACH_X
                    val y = eye.top + lookY * eye.roomY * REACH_Y
                    drawImage(irises[i], topLeft = Offset(x, y))
                    if (blink > 0f) {
                        // The upper lid sweeps down over the whole opening, its lashes along the leading edge.
                        val socket = eye.socket
                        val edge = socket.top - 1f + (socket.height + 2f) * blink
                        drawRect(
                            Brush.verticalGradient(listOf(lid, lid, lash), socket.top - 1f, edge),
                            topLeft = Offset(socket.left, socket.top - 1f),
                            size = Size(socket.width, edge - socket.top + 1f),
                        )
                    }
                }
            }
        }
    }
}
